CREATE TABLE aziende(
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	ragione_sociale VARCHAR(30) NOT NULL,
	indirizzo VARCHAR(40) NOT NULL,
	cap VARCHAR(5) NOT NULL,
	città VARCHAR(20) NOT NULL,
	provincia VARCHAR(20) NOT NULL,	
	PRIMARY KEY(id)
);